name: dashed_border
description: "A Flutter package for customizable dashed, dotted, and solid borders with support for rounded corners and animations."
version: 1.0.2
homepage: https://github.com/Toasty360/dashed_border
repository: https://github.com/Toasty360/dashed_border
issue_tracker: https://github.com/Toasty360/dashed_border/issues
environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
